name: reader 
base: core18 
version: '0.1' 
summary: Single-line elevator pitch for your amazing snap 
description: |
  this is a snap for refid based attendance

grade: stable 
confinement: devmode 
apps:
  reader:
    command: reader
parts:
  reader:
    plugin: python
    source: https://github.com/Arun1930/reader.git
 
